### ISSUE TITLE
Support KotlinLang

### ISSUE THREAD

**Issue by demand2k** [realm/realm-java#509]
Current version of Realm (0.72) not working with Kotlin (http://kotlinlang.org/).
A have an exception "Caused by: io.realm.exceptions.RealmException: Could not find the generated ValidationList class", I think it's because there is no private fields with getters and setters in my model.
Kotlin don't recommend to create default getters/setters for properties.
Is it possible to use Realm with Kotlin?

**Comment by shvelo** [comment]
Any progress?

**Comment by cmelchior** [comment]
To my knowledge Kotlin still doesn't support Annotation Processing which Realm relies heavily upon. See https://youtrack.jetbrains.com/issue/KT-5714 and https://youtrack.jetbrains.com/issue/KT-5720

Until that is fixed there is not much that we can do.

**Comment by m00sey** [comment]
For clarity, as @VerachadW and @demand2k pointed out you can happily use Realm with Kotlin by creating your models in Java.

**Comment by kneth** [comment]
Is there a Kotlin user who can write down how to do it? We happily link to a short guide.

**Comment by m00sey** [comment]
I have provided a small and pretty crude example - but it is enough to get anyone started.

https://github.com/m00sey/RealmKotlinExample

**Comment by kneth** [comment]
@m00sey thanks! I haven't tried Kotlin before but your example looks clean so I have to try Kotlin :-)

**Comment by kneth** [comment]
@m00sey We have added a link to your examples in our documentation (see http://realm.io/docs/java/#faq).

**Comment by cmelchior** [comment]
Interesting. It seems Kotlin will start supporting annotation processing in the near future: http://blog.jetbrains.com/kotlin/2015/05/kapt-annotation-processing-for-kotlin/?utm_source=twitterfeed&utm_medium=twitter&utm_campaign=Feed%3A+kotlin+%28Project+Kotlin%29

**Comment by cypressious** [comment]
Kotlin M12 with annotation processing was released today. I added

```kapt 'com.jakewharton:butterknife:5.1.1'```

to my build configuration and tried the following simple class

```Kotlin
open class Ticket() : RealmObject() {
    @PrimaryKey open var id: String = ""
}
```

but unfortunately no proxy class was generated. Any insights?

**Comment by yanex** [comment]
`@PrimaryKey` annotation has a `SOURCE` retention policy (`@Retention(RetentionPolicy.SOURCE)`).
Only `CLASS` and `RUNTIME` policies are supported by kapt now.

**Comment by cypressious** [comment]
Right! What can we do about this?

**Comment by cypressious** [comment]
It seems I have found a workaround. First I copied the source of `PrimaryKey` to my project and replaced the retention policy:

```java
package io.realm.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Retention(RetentionPolicy.CLASS)
@Target({ElementType.FIELD})
public @interface PrimaryKey {
}
```

I expected the compiler to complain about the duplicate class but it didn't. Then I added the `RealmClass` annotation to my `Ticket` class:

```kotlin
@RealmClass
open class Ticket(
        @PrimaryKey open var id: String = ""
) : RealmObject()
``` 

Now the proxy class seems to be correctly generated.

**Comment by cmelchior** [comment]
Changes to annotations has been merged to master so Realm should now work with Kotlin M12 (thanks @cypressious). It should be available shortly as a ```0.81-SNAPSHOT``` release. An example of how it works can be found here: https://github.com/realm/realm-java/tree/master/examples/kotlinExample

Please let us know if there is any caveats or edge cases that still doesn't work or require special setup.

**Comment by deviant-studio** [comment]
I tried Kotlin M14 and Realm 0.83.1
Still doesn't work

Note: Version 0.83.0 of Realm is now available: http://static.realm.io/downloads/java/latest
Note: Processing class UserRealm
error: The fields of the model must be private
Note: Creating DefaultRealmModule
warning: File for type 'io.realm.DefaultRealmModule' created in the last round will not be subject to annotation processing.
warning: File for type 'io.realm.DefaultRealmModuleMediator' created in the last round will not be subject to annotation processing.
warning: The following options were not recognized by any processor: '[kapt.kotlin.generated]'
1 error
2 warnings

 FAILED

**Comment by cmelchior** [comment]
Thanks @deviant-studio We will look into it.

**Comment by cypressious** [comment]
@deviant-studio Show us your model classes.

**Comment by deviant-studio** [comment]
Ok. I guess it fails only when 'lateinit' fields are used. Replaced to nullable (var s:String?=null) and now it compiles. Is it possible to support lateinit fields?

**Comment by cypressious** [comment]
lateinit generates public fields, I guess Realm doesn't like it

**Comment by cmelchior** [comment]
No, not yet. That will be fixed as part of https://github.com/realm/realm-java/issues/909

**Comment by kneth** [comment]
Kotlin 1.0 is approaching: http://blog.jetbrains.com/kotlin/2015/10/kotlin-1-0-beta-candidate-is-out/

**Comment by ubertao** [comment]
Gradle build failed with 0.85.1.

I created an empty project following the steps from [kotlin tutorial](https://kotlinlang.org/docs/tutorials/kotlin-android.html), then modified `build.gradle` according to [example](https://github.com/realm/realm-java/blob/v0.85.1/examples/kotlinExample/build.gradle) in realm repo.

Here's the error message from gradle console:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: io/realm/annotations/RealmClass
```

And here's my `build.gradle`:

```gradle
buildscript {
    ext.kotlin_version = '1.0.0-beta-1038'
    ext.realm_version = '0.85.1'
    repositories {
        jcenter()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 23
    buildToolsVersion "22.0.1"

    defaultConfig {
        applicationId "com.ubertao.ktrealm"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "io.realm:realm-android:$realm_version"
    compile "io.realm:realm-annotations:$realm_version"
    kapt "io.realm:realm-annotations-processor:$realm_version"
}
```

I haven't added any code using Realm in the project.

I'm using Android Studio 1.4.

**Comment by emanuelez** [comment]
Hmmm... can you try adding

```
kapt "io.realm:realm-annotations:$realm_version"
```

after the other `kapt` line?

**Comment by ubertao** [comment]
Now using:
```
compile "io.realm:realm-android:$realm_version"
compile "io.realm:realm-annotations:$realm_version"
kapt "io.realm:realm-annotations-processor:$realm_version"
kapt "io.realm:realm-annotations:$realm_version"
```
Got the following error message after adding a `Person` class:

```
...

:app:compileDebugJavaWithJavac
Note: Processing class Person
Note: Creating DefaultRealmModule
Warning:The following options were not recognized by any processor: '[kapt.kotlin.generated]'

:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources
:app:preDexDebug
:app:dexDebug
AGPBI: {"kind":"simple","text":"UNEXPECTED TOP-LEVEL EXCEPTION:","sources":[{}]}
AGPBI: {"kind":"simple","text":"com.android.dex.DexException: Multiple dex files define Lio/realm/annotations/Ignore;","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.merge.DexMerger.merge(DexMerger.java:189)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.dexer.Main.run(Main.java:246)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.dexer.Main.main(Main.java:215)","sources":[{}]}
AGPBI: {"kind":"simple","text":"\tat com.android.dx.command.Main.main(Main.java:106)","sources":[{}]}


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_72.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2
```

**Comment by cmelchior** [comment]
@ubertao I just upgraded our Kotlin example here, where you can see a working solution:  https://github.com/realm/realm-java/blob/cm/copyfromrealm/examples/kotlinExample/build.gradle

**Comment by ubertao** [comment]
The solution seems work with 0.86.0-SNAPSHOT but not 0.85.1. I hope next version will be out soon.
BTW, can you update your example here with RealmClass annotation?
https://github.com/realm/realm-java/tree/master/examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model

Thanks.

**Comment by ubertao** [comment]
Just tried 0.86.0 release, build is still failing. Seems the problem is caused by missing dependencies in published POM files: https://jcenter.bintray.com/io/realm/realm-annotations-processor/0.86.0/:realm-annotations-processor-0.86.0.pom

**Comment by cmelchior** [comment]
Yes, we have problem with our current real distribution package compared to the SNAPSHOT's. You need to manually add JavaWriter currently, sorry: https://github.com/realm/realm-java/issues/1861

**Comment by ubertao** [comment]
It cannot find RealmClass:

    java.lang.NoClassDefFoundError: io/realm/annotations/RealmClass

**Comment by matthewsurfshack** [comment]
I'm having the same NoClassDefFoundError: io/realm.annotations/RealmClass. 

I also tried downloading the realm-java examples and running the kotlinExample. If I leave it on the 0.87.0-snapshot it does not compile complaining that it can't find io.realm:realm-gradle-plugin:0.87.0-SNAPSHOT.

If I change the version.txt to use 0.86.1 ( the current release ) the kotlinExample fails with the same java.lang.NoClassDefFoundError: io/realm/annotations/RealmClass as my project.

**Comment by cmelchior** [comment]
@matthewsurfshack Where did you get the examples from? Did you download it from our website or cloned our github repository?

**Comment by matthewsurfshack** [comment]
@cmelchior cloned from github.

**Comment by cmelchior** [comment]
Hi @matthewsurfshack We have added a fix to the Kotlin example, so it should be working now.

**Comment by ubertao** [comment]
My app still fail to build with 0.87.0 release. Here is a sample project that can reproduce the error: https://github.com/ubertao/KtRealm

**Comment by cmelchior** [comment]
Hi @ubertao 
Can you try adding `kapt "io.realm:realm-annotations:$realm_version"` to your `build.gradle`. It fixed it last I tried, but for some reason it kept on working even after removing it.

**Comment by ubertao** [comment]
Yes, now build passes with 2 lines of `kept`:
```gradle
    kapt "io.realm:realm-annotations-processor:$realm_version"
    kapt "io.realm:realm-annotations:$realm_version"
```

Thanks!

**Comment by jturolla** [comment]
any update on this? Closed?

**Comment by Zhuinden** [comment]
@jturolla it **should** work now, so I'm surprised this is open

**Comment by cmelchior** [comment]
Yes, that is an mistake. We should be fully compatible with Kotlin right now.
