### ISSUE TITLE
Realm 4.3.1 ClassNotFoundException: Didn't find class "io.realm.internal.async.RealmThreadPoolExecutor"

### ISSUE THREAD

**Issue by lam-amsiq** [realm/realm-java#5603]
#### Goal

Setup realm

#### Expected Results

Realm configured

#### Actual Results

```
12-08 09:26:29.513 8300-8300/com.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                          Process: com.app, PID: 8300
                                                          java.lang.NoClassDefFoundError: Failed resolution of: Lio/realm/internal/async/RealmThreadPoolExecutor;
                                                              at io.realm.BaseRealm.<clinit>(BaseRealm.java:72)
                                                              at io.realm.Realm.init(Realm.java)
                                                              at com.app.controllers.MyApplication.setupRealm(MyApplication.java:142)
                                                              at com.app.controllers.MyApplication.onCreate(MyApplication.java:83)
                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
                                                              at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.async.RealmThreadPoolExecutor" on path: DexPathList[[zip file "/data/app/com.app-2/base.apk"],nativeLibraryDirectories=[/data/app/com.app-2/lib/arm64, /data/app/com.app-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                              at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                              at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                              at io.realm.BaseRealm.<clinit>(BaseRealm.java:72) 
                                                              at io.realm.Realm.init(Realm.java) 
                                                              at com.app.controllers.MyApplication.setupRealm(MyApplication.java:142) 
                                                              at com.app.controllers.MyApplication.onCreate(MyApplication.java:83) 
                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032) 
                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885) 
                                                              at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                              at android.os.Looper.loop(Looper.java:154) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample
Fails at Realm.init(this);, where this is instance of Application
```java
    private void setupRealm() {
        Realm.init(this);
        try {
            RealmConfiguration newConfig = new RealmConfiguration.Builder().schemaVersion(2).deleteRealmIfMigrationNeeded().compactOnLaunch().build();
            Realm.setDefaultConfiguration(newConfig);
        } catch (RuntimeException ignore) {}
    }
```

#### Version of Realm and tooling
Realm version(s): 4.3.1

Which Android version and device: Any

**Comment by Zhuinden** [comment]
At first glance I'd say this is a duplicate of https://github.com/realm/realm-java/issues/5601#issuecomment-349948595

**Comment by lam-amsiq** [comment]
The fix in #5601 (extends MultiDexApplication instead of extends Application.) didn't fix the issue.

Just for clarification, the issue only appears in Realm 4.3.0 and 4.3.1.

**Comment by Zhuinden** [comment]
Clean + rebuild?

**Comment by lam-amsiq** [comment]
No effect. The error happens at runtime

**Comment by Zhuinden** [comment]
Are you 100% sure you don't have a `compile 'io.realm:realm-android:0.82.2` in some build gradle you are using?

**Comment by lam-amsiq** [comment]
```
allprojects {
    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
    repositories {
        jcenter()
        mavenLocal()
        maven { url 'https://maven.fabric.io/public' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        maven { url "https://jitpack.io" }
        maven {
            url "https://maven.google.com"
        }
        google()
    }

    buildscript {
        repositories {
            jcenter()
            mavenLocal()
            maven { url 'https://maven.fabric.io/public' }
            google()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:3.0.1'
            classpath 'com.google.gms:google-services:3.1.2'
            classpath 'io.realm:realm-gradle-plugin:4.3.1'
            classpath 'io.fabric.tools:gradle:1.24.5'
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }
    }
}
```
```
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'

ext {
    AAVersion = '4.4.0'
    Glide = '4.4.0'
    Firebase = '11.6.2'
    RetrofitVersion = '2.3.0'
    SupportVersion = '27.0.1'
    OkhttpVersion = '3.9.1'
    rxlifecycle = '2.2.0'
    gson = '2.8.2'
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('libs/GoogleConversionTrackingSdk-2.2.4.jar')
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    // Multidex
    compile 'com.android.support:multidex:1.0.2'
    // Android annotations preprocessor
    annotationProcessor 'org.androidannotations:androidannotations:' + AAVersion
    // Android annotations
    compile 'org.androidannotations:androidannotations-api:' + AAVersion
    // Gson
    compile 'com.google.code.gson:gson:' + gson
    // Retrofit
    compile 'com.squareup.retrofit2:retrofit:' + RetrofitVersion,
            'com.squareup.retrofit2:converter-gson:' + RetrofitVersion,
            'com.squareup.retrofit2:adapter-rxjava2:' + RetrofitVersion
    // Okhhtp
    compile 'com.squareup.okhttp3:logging-interceptor:' + OkhttpVersion
    // RxJava
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.7'
    compile 'com.github.davidmoten:rxjava2-extras:0.1.13'
    compile 'com.trello.rxlifecycle2:rxlifecycle:' + rxlifecycle,
            'com.trello.rxlifecycle2:rxlifecycle-components:' + rxlifecycle
    //Picasso
    compile 'com.squareup.picasso:picasso:2.5.3-SNAPSHOT'
    compile 'jp.wasabeef:picasso-transformations:2.1.2'
    // Glide
    compile 'com.github.bumptech.glide:glide:' + Glide
    // Glide annotations
    annotationProcessor 'com.github.bumptech.glide:compiler:' + Glide
    // Glide tranformations
    compile 'jp.wasabeef:glide-transformations:3.0.1'
    // Google Play Services
    compile 'com.google.firebase:firebase-messaging:' + Firebase,
            'com.google.firebase:firebase-analytics:' + Firebase,
            'com.google.firebase:firebase-ads:' + Firebase,
            'com.google.firebase:firebase-config:' + Firebase
    // Android support libraries
    compile 'com.android.support:customtabs:' + SupportVersion,
            'com.android.support:appcompat-v7:' + SupportVersion,
            'com.android.support:cardview-v7:' + SupportVersion,
            'com.android.support:support-v13:' + SupportVersion,
            'com.android.support:design:' + SupportVersion
    // Fabric.io
    compile('com.crashlytics.sdk.android:crashlytics:2.8.0@aar') {
        transitive = true;
    }
    // Facebook
    compile 'com.facebook.android:facebook-android-sdk:4.+'
    // ShortCutBadger
    compile 'me.leolin:ShortcutBadger:1.1.18@aar'
    // Romandanylyk page_indicator
    compile 'com.romandanylyk:pageindicatorview:0.2.0@aar'
    // Circle page indicator
    compile 'me.relex:circleindicator:1.2.2@aar'
    // Material Dialogs
    compile 'com.afollestad.material-dialogs:core:0.9.6.0'
    // ImageCropper
    compile 'com.theartofdev.edmodo:android-image-cropper:2.5.1'
    // Joda - time
    compile 'joda-time:joda-time:2.9.9'
    // Blur
    compile 'com.eightbitlab:blurview:1.3.3'
}
```

**Comment by Zhuinden** [comment]
Interesting. Unfortunately I don't have any guesses left, hopefully the Realm team can figure out what's up.

**Comment by beeender** [comment]
Do you have `multiDexEnabled true` in your gradle file?
Also if the problem still exists, would you please share the full gradle log with `--info`?

**Comment by lam-amsiq** [comment]
multiDexEnabled is set to true.
MyApplication:
```java
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
```

Log attached
[Realm crashlog issue 5603.txt](https://github.com/realm/realm-java/files/1547043/Realm.crashlog.issue.5603.txt)

**Comment by beeender** [comment]
@lam-amsiq I mean the **gradle build** log :)

try with `./gradlew assemble > log.txt` if you are under unix like system. for windows you may need to use `gradle.bat`.

**Comment by lam-amsiq** [comment]
[log.txt](https://github.com/realm/realm-java/files/1547103/log.txt)

**Comment by Zhuinden** [comment]
@lam-amsiq this might seem like a silly question, but the application class is specified in AndroidManifest.xml as `android:name="appclass"` rightM

**Comment by lam-amsiq** [comment]
yes, it is

**Comment by GulajavaMinistudio** [comment]
Im also experienced this problem when i updated my realm library from 4.2.0 to 4.3.1 . 
When using Realm 4.2.0 , the multidex is running fine. But after upgrading to 4.3.1 , the multidex for realm library and other library is broken.

Also, there's some different when compiling project with Realm 4.3.1 , this library triggers D8 compiler to doing multidex. You also can found it in lam-amsiq log.txt above .

"
```
:app:transformClassesWithDexBuilderForBeta
D8 is used to build dex.
:app:transformClassesWithMultidexlistForBeta
:app:transformDexArchiveWithDexMergerForBeta
D8 is used to merge dex.
com/google/android/gms/internal/aou.class
com/facebook/share/widget/CreateAppGroupDialog.class
io/realm/ab.class
```
"

I've been disabled the D8 compiler from gradle.properties, but the multidex is broken when using with Realm 4.3.1

**Comment by defaultbr** [comment]
+1

Extends MultiDexApplication - yes 
Application in Manifest - yes
MultiDex.install(this) - yes (tried switching this and extends to on/off, same issue)
MultidexEnabled true in build.gradle - yes
Realm Version 4.3.1
Android Version 4.4.2

**Comment by brucemax** [comment]
I got java.lang.NoClassDefFoundError: io.realm.Realm during update gradle and other libs.
Returning to stable gradle do the trick:
Change
        classpath 'com.android.tools.build:gradle:3.1.0-alpha06'
to
        classpath 'com.android.tools.build:gradle:3.0.1'

**Comment by Zhuinden** [comment]
Then this answer should help  https://github.com/realm/realm-java/issues/5640#issuecomment-355497076

**Comment by Zhuinden** [comment]
@brucemax this should be fixed in 4.3.2 released today

**Comment by nhachicha** [comment]
Hi @lam-amsiq @defaultbr @GulajavaMinistudio 
any luck with `4.3.2` or [4.3.3-SNAPSHOT](https://github.com/realm/realm-java#using-snapshots)?

**Comment by defaultbr** [comment]
@nhachicha  nope, my solution was to do a big clean in the dependencies, code and reduce the methods count to under the 65k limit, so now i can build without MULTIDEX!

@nhachicha build a debug apk, analyze which dependencies has more methods, remove/change it and than build without Multidex


not tried 4.3.3-SNAPSHOT yet

**Comment by leslieharland** [comment]
extends MultiDexApplication solved the problem 

 dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "io.realm:realm-gradle-plugin:5.0.0"
    }

**Comment by CyxouD** [comment]
This issue appeared today without making any changes from my side, @brucemax solution helped. In my case I updated `com.android.tools.build:gradle:3.1.0-alpha05` to `com.android.tools.build:gradle:3.1.0`
