### ISSUE TITLE
NoClassDefFoundError (SafeVarargs) API 17

### ISSUE THREAD

**Issue by gremzor** [realm/realm-java#5463]
#### Goal

> Use realm-java on android api level 17

#### Expected Results

> realm-java does not crash on api level 17

#### Actual Results

>  I am encountering the following exception when I upgrade my project from 3.7.2 to 4.1.0: java.lang.NoClassDefFoundError: java/lang/SafeVarargs. This is only occurring on api level 17, all apis above 17 seem to work fine. Before this crash I get an error specifically regarding RealmList: 
E/dalvikvm: Unable to resolve Lio/realm/RealmList; annotation class 7880

#### Steps & Code to Reproduce

> Fairly certain this is occurring due to the recent use of the SafeVarargs annotation in RealmList and RealmConfiguration. This can be reproduced by using a RealmList within a project on the api level 17 emulator.

#### Version of Realm and tooling
Realm version(s): 4.1.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Emulator, API 17.

**Comment by nhachicha** [comment]
Hi @gremzor good catch! the annotation should be supported since [Java 7](https://docs.oracle.com/javase/7/docs/api/java/lang/SafeVarargs.html) but the class was not added to Android until API 19, we'll remove it
