### ISSUE TITLE
 java.lang.NoClassDefFoundError: io.realm.rx.RealmObservableFactory

### ISSUE THREAD

**Issue by zakariabelaziz** [realm/realm-java#2720]
Hello and thanks for your support. I have a probleme since i upgraded android studio from 1.5 to 2.1. Realm class arent found on apk and i dont use Instant run. So the fact is that im on this probleme since   some few days and i begin to see no issue. And like im in a hurry i need to make a choice delete Realm from my project or try harder to fix it. I have read some issue and tryed the few methods found there but no one worked. Here is my build gradle.

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'com.google.gms:google-services:2.0.0-alpha5'
        classpath "io.realm:realm-gradle-plugin:0.89.1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

And there my app build 

```
apply plugin: 'com.android.application'
//apply plugin: 'com.google.gms.google-services'
apply plugin: 'realm-android'
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "fr.jds.app"
        minSdkVersion 17
        targetSdkVersion 23

        // Enabling multidex support.
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        javaMaxHeapSize "4g"
    }

}

repositories {
    mavenCentral()
}




dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile project(path: ':backend', configuration: 'android-endpoints')



   // compile 'com.google.android.gms:play-services:8.4.0'


    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
   compile 'io.realm:realm-android:0.87.4'
    compile 'com.facebook.android:facebook-android-sdk:4.11.0'



    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.google.android.gms:play-services-maps:8.4.0'
    compile 'com.google.android.gms:play-services-location:8.4.0'
    compile 'com.google.android.gms:play-services-analytics:8.4.0'
    compile 'com.google.android.gms:play-services-ads:8.4.0'





    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:recyclerview-v7:23.3.0'
    //  compile 'com.android.support:multidex:1.0.1'
}

apply plugin: 'com.google.gms.google-services'
```

Here is the error :  E/AndroidRuntime: FATAL EXCEPTION: main
                                                            Process: fr.jds.app, PID: 14719
                                                            java.lang.NoClassDefFoundError: io.realm.rx.RealmObservableFactory
 and the code that trow the error : ` // Configure Realm for the application
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).build();`

I hope that it will point you where i doing wrong. Since it been some few days that i have been trying to fix it, it's not the original code that was working, i might have some archive (and yes now i have implemented Git on my project my biggest mistake was to not set it first).

Thanks for your answer

**Comment by Zhuinden** [comment]
You added **two** realm version:

    classpath "io.realm:realm-gradle-plugin:0.89.1"

in your project build gradle and

    compile 'io.realm:realm-android:0.87.4'

In your module-level build gradle

You should keep only one of those. Probably the new one.

**Comment by zakariabelaziz** [comment]
sry for the mistake when i copy paste i forget to make one of them in commentary, but that doesnt change the issue you know

**Comment by cmelchior** [comment]
@zakariabelaziz 
What happens if you run `./gradlew clean assemble --refresh-dependencies` from the commandline?

**Comment by beeender** [comment]
@zakariabelaziz Does above comments solve your issue?

**Comment by beeender** [comment]
Close due to no response. Feel free to reopen it if necessary.
