### ISSUE TITLE
Field "default" is ignored in a RealmObject

### ISSUE THREAD

**Issue by AoDevBlue** [realm/realm-java#6361]
#### Goal

Define a `RealmObject` with a field named `default`.

#### Actual Results

The `RealmObject` proxy ignores the field named `default`.

This looks like a reserved word since it works with other names, but I couldn't find any list of such reserved words. If I missed it in the documentation, where is it?

#### Steps & Code to Reproduce

See this sample project https://github.com/AoDevBlue/DefaultColumnRealm

The object definition:

```
open class ExampleObject : RealmObject() {
    @PrimaryKey
    var id: Long = 0
    var default: String? = null
    var other: String? = null
}
```

The generated proxy has the following column info:

```
static final class ExampleObjectColumnInfo extends ColumnInfo {
        long maxColumnIndexValue;
        long idIndex;
        long otherIndex;

        ExampleObjectColumnInfo(OsSchemaInfo schemaInfo) {
            super(2);
            OsObjectSchemaInfo objectSchemaInfo = schemaInfo.getObjectSchemaInfo("ExampleObject");
            this.idIndex = addColumnDetails("id", "id", objectSchemaInfo);
            this.otherIndex = addColumnDetails("other", "other", objectSchemaInfo);
            this.maxColumnIndexValue = objectSchemaInfo.getMaxColumnIndex();
        }

        ...
}
```

#### Version of Realm and tooling

Realm version(s): 5.8.0

Realm Sync feature enabled: No

Android Studio version: 3.2.1

Android Build Tools version: 3.2.1

Gradle version: 4.6

Which Android version and device(s): Nexus 5X (Android 8.1.0)

**Comment by AoDevBlue** [comment]
Adding to it as an afterthought: if it's indeed a reserved word, maybe a compilation error should be raised.

**Comment by cmelchior** [comment]
Realm itself does not have any reserved keywords for properties, but language restrictions might prohibit defining some model classes. `default` is a reserved keyword in Java, and the Realm annotation processor runs on Java stubs generated by . kapt, so I suspect that it breaks somewhere in that process.

I'm actually surprised that your app compiles at all, I would expect it to fail entirely.

**Comment by AoDevBlue** [comment]
I didn't think about Java itself, but it makes sense.

It still compiles fine and it actually used to work using realm-java 3.0.0. I was upgrading Realm when I caught that.

**Comment by Zhuinden** [comment]
Let us be thankful that you can do this:

    @field:RealmField("default")
    var isDefault: String? = null

And you'll still keep compatibility without having to migrate.

**Comment by AoDevBlue** [comment]
@cmelchior It's indeed related to Java 8.

Using Realm 3.0.0 but with

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

leads to the same problem.

**Comment by cmelchior** [comment]
Since this a language restriction there isn't much Realm can do about it. The `RealmField` annotation above should be a sufficient workaround in most (all?) cases. Closing
