### ISSUE TITLE
Realm Gradle plugin should process R classes from jar

### ISSUE THREAD

**Issue by gavra0** [realm/realm-java#6531]
Starting with Android Gradle plugin 3.6.0-alpha01, R.java is not generated any more, and R clasess are compiled separately from the rest of the sources to R.jar e.g. `./app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/debug/R.jar`.

This means that the `RealmTransformer` should be able to process project classes coming from both directories and jars. Looking at implementation of `BuildTemplate.categorizeClassNames` it seems that classes coming from jars are in not processed.

Related issue: https://issuetracker.google.com/130965921#comment14

**Comment by cmelchior** [comment]
Thanks. Yes, we should fix this.

**Comment by cmelchior** [comment]
I can reproduce this with `3.6.0-alpha05` and our `/examples/moduleExample`. It crashes with:

```
2019-08-02 14:49:43.548 11045-11045/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.realm.examples.realmmultiprocessexample, PID: 11045
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/appcompat/R$drawable;
        at android.support.v7.widget.k.<clinit>(:107)
        at android.support.v7.widget.k.a(:84)
        at android.support.v7.widget.v0.c(:85)
        at android.support.v7.app.f.<init>(:128)
        at android.support.v7.app.j.<init>(:149)
        at android.support.v7.app.h.<init>(:56)
        at android.support.v7.app.i.<init>(:31)
        at android.support.v7.app.g.<init>(:31)
        at android.support.v7.app.e.a(:198)
        at android.support.v7.app.e.a(:183)
        at android.support.v7.app.c.h(:519)
        at android.support.v7.app.c.onCreate(:70)
        at io.realm.examples.realmmultiprocessexample.MainActivity.onCreate(:60)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.appcompat.R$drawable" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/io.realm.examples.realmmultiprocessexample-qdYfMRN-0WyQ_cCQY1rLNA==/base.apk"],nativeLibraryDirectories=[/data/app/io.realm.examples.realmmultiprocessexample-qdYfMRN-0WyQ_cCQY1rLNA==/lib/x86, /data/app/io.realm.examples.realmmultiprocessexample-qdYfMRN-0WyQ_cCQY1rLNA==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
```

**Comment by cmelchior** [comment]
I can reproduce with `3.6.0-alpha05` and the `/examples/multiprocessExample`

```
08-02 14:56:55.008 11742 11742 E AndroidRuntime: Process: io.realm.examples.realmmultiprocessexample, PID: 11742
08-02 14:56:55.008 11742 11742 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/appcompat/R$drawable;
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.widget.k.<clinit>(:107)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.widget.k.a(:84)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.widget.v0.c(:85)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.f.<init>(:128)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.j.<init>(:149)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.h.<init>(:56)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.i.<init>(:31)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.g.<init>(:31)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.e.a(:198)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.e.a(:183)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.c.h(:519)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.support.v7.app.c.onCreate(:70)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at io.realm.examples.realmmultiprocessexample.MainActivity.onCreate(:60)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7136)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7127)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
08-02 14:56:55.008 11742 11742 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(
```

Many of the other example projects seem to work fine though, which strikes me as a bit odd.

**Comment by cmelchior** [comment]
Problem was that the JAR files were not correctly copied to the output folders again which is why the transformer worked correctly, but the project crashes at runtime. This should be fixed in #6575
