### ISSUE TITLE
java.lang.NoSuchMethodError , java.lang.StackOverflowError after update to 3.1.3

### ISSUE THREAD

**Issue by saeedrooyekhat** [realm/realm-java#4541]
My project was updated from Realm 2.3.1 to Realm Version 3.1.3,

in the following code
```java

  public class BlockListAdapter extends RealmBasedRecyclerViewAdapter<RealmRegisteredInfo, BlockListAdapter.ViewHolder> {

        public BlockListAdapter(Context context, RealmResults<RealmRegisteredInfo> realmResults) {
            super(context, realmResults, true, true, false, ""); // error line
        }

.
.
.
}

```

I got the following error
```java
java.lang.NoSuchMethodError: io.realm.RealmResults.getTableOrView
at io.realm.RealmBasedRecyclerViewAdapter.<init>(RealmBasedRecyclerViewAdapter.java:167)
at io.realm.RealmBasedRecyclerViewAdapter.<init>(RealmBasedRecyclerViewAdapter.java:133)
```

also i have another problem. when i get instance from realm encounter to this error

```java
   Realm realm = Realm.getDefaultInstance();


   java.lang.StackOverflowError
at java.lang.ThreadLocal$Values.cleanUp(ThreadLocal.java:254)
at java.lang.ThreadLocal$Values.put(ThreadLocal.java:381)
at java.lang.ThreadLocal.set(ThreadLocal.java:91)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:172)
at io.realm.Realm.getDefaultInstance(Realm.java:211)
```
Both of these errors occurred after Realm updated

#### Version of Realm and tooling
Realm version(s): 3.1.3

Realm sync feature enabled:no

Android Studio version: 2.2.1

Which Android version and device: 4 and 5

**Comment by kneth** [comment]
@saeedrooyekhat Are you using the Realm adapters? If so, you need to upgrade that library too.

**Comment by Zhuinden** [comment]
NoSuchMethodError comes from that the `RealmBasedRecyclerViewAdapter` you're using is outdated for Realm 3.0.0 and uses package internal methods that no longer exist. 

You should switch to the new `RealmRecyclerViewAdapter` provided by `realm-android-adapters` which also provides animations for your elements. 

----

The second one is probably caused in a RealmChangeListener calling `executeTransaction` somewhere in your code, one where the `RealmChangeListener`'s `onChange()` method calls `Realm.getDefaultInstance()` as its first line.

**Comment by Zhuinden** [comment]
@kneth he is using the Thorben Primke `realm-recyclerview` library

**Comment by kneth** [comment]
And @thorbenprimke hasn't updated it for a while.

**Comment by Zhuinden** [comment]
Yes, RealmRecyclerViewAdapter is better choice. Especially now that it provides animations, and no need to hack it out based on primary key and manual diffing.

**Comment by saeedrooyekhat** [comment]
@Zhuinden i have this code
```java
new Handler(G.currentActivity.getMainLooper()).post(new Runnable() {
            @Override
            public void run() {

                final Realm realm = Realm.getDefaultInstance();
                final ProtoClientGetRoomHistory.ClientGetRoomHistoryResponse.Builder builder = (ProtoClientGetRoomHistory.ClientGetRoomHistoryResponse.Builder) message;
                final ArrayList<RealmRoomMessage> realmRoomMessages = new ArrayList<>();
                realm.executeTransactionAsync(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {

                        final long userId = realm.where(RealmUserInfo.class).findFirst().getUserId();
                        for (ProtoGlobal.RoomMessage roomMessage : builder.getMessageList()) {
                            if (roomMessage.getAuthor().hasUser()) {
                                HelperInfo.needUpdateUser(roomMessage.getAuthor().getUser().getUserId(), roomMessage.getAuthor().getUser().getCacheId());
                            }
                            realmRoomMessages.add(RealmRoomMessage.putOrUpdate(roomMessage, Long.parseLong(identity)));
                            if (roomMessage.getAuthor().getUser().getUserId() != userId) { // show notification if this message isn't for another account
                                if (!G.isAppInFg) {
                                    G.helperNotificationAndBadge.checkAlert(true, ProtoGlobal.Room.Type.CHAT, Long.parseLong(identity));
                                }
                            }
                        }
                    }
                }, new Realm.Transaction.OnSuccess() {
                    @Override
                    public void onSuccess() {
                        realm.close();
                        G.onClientGetRoomHistoryResponse.onGetRoomHistory(Long.parseLong(identity), builder.getMessageList().get(0).getMessageId(), builder.getMessageList().get(builder.getMessageCount() - 1).getMessageId()); // Callback
                    }
                }, new Realm.Transaction.OnError() {
                    @Override
                    public void onError(Throwable error) {
                        realm.close();
                    }
                });
            }
        });
```
and after call onGetRoomHistory this code will be executed

```java
 G.onClientGetRoomHistoryResponse = new OnClientGetRoomHistoryResponse() {
            @Override
            public void onGetRoomHistory(final long roomId, final long startMessageId, long endMessageId) {

 .
.
.
                Realm realm = Realm.getDefaultInstance();
                realm.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
 
.
.
                    }
                });
                realm.close();

                onMessageReceive.onMessage(roomId, startMessageId, endMessageId, gapReached);
            }
        };
```

in this codes i don't use from RealmChangeListener , but i got this error!

**Comment by saeedrooyekhat** [comment]
for 
```java
java.lang.NoSuchMethodError: io.realm.RealmResults.getTableOrView 
```
 will be used from realm-android-adapters .

but for 
```java
java.lang.StackOverflowError
```
 i don't have any solution!

**Comment by Zhuinden** [comment]
I am not sure about the cause of this stack overflow error, especially considering nothing in regards to the `RealmCache` has been changed, but you can try reversing the order of `close` and the `callback` methods

``` java
                        G.onClientGetRoomHistoryResponse.onGetRoomHistory(Long.parseLong(identity), builder.getMessageList().get(0).getMessageId(), builder.getMessageList().get(builder.getMessageCount() - 1).getMessageId()); // Callback
                      realm.close();
```

and

``` java
                onMessageReceive.onMessage(roomId, startMessageId, endMessageId, gapReached);
                realm.close();
            }
```

**Comment by saeedrooyekhat** [comment]
my older code was
```java
G.onClientGetRoomHistoryResponse.onGetRoomHistory(Long.parseLong(identity), builder.getMessageList().get(0).getMessageId(), builder.getMessageList().get(builder.getMessageCount() - 1).getMessageId()); // Callback
realm.close();
```
and just to test this mode was changed to

```java
realm.close();
G.onClientGetRoomHistoryResponse.onGetRoomHistory(Long.parseLong(identity), builder.getMessageList().get(0).getMessageId(), builder.getMessageList().get(builder.getMessageCount() - 1).getMessageId()); // Callback

```

**Comment by Zhuinden** [comment]
This error might be device specific, what device is this stack overflow errorr happening on?

**Comment by beeender** [comment]
what is the full stacktrace for the stack overflow issue?

**Comment by saeedrooyekhat** [comment]
@beeender error message is
```java
java.lang.StackOverflowError
at java.lang.ThreadLocal$Values.cleanUp(ThreadLocal.java:254)
at java.lang.ThreadLocal$Values.put(ThreadLocal.java:381)
at java.lang.ThreadLocal.set(ThreadLocal.java:91)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:172)
at io.realm.Realm.getDefaultInstance(Realm.java:211)
```

after this lines show my code line

```java
G.onClientGetRoomHistoryResponse = new OnClientGetRoomHistoryResponse() {
            @Override
            public void onGetRoomHistory(final long roomId, final long startMessageId, long endMessageId) {

.
.
.
                Realm realm = Realm.getDefaultInstance(); // error line
                realm.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
 
.
.
                    }
                });
                realm.close();

                onMessageReceive.onMessage(roomId, startMessageId, endMessageId, gapReached);
            }
        };
```

**Comment by Zhuinden** [comment]
only relevant thing I found is http://stackoverflow.com/questions/3869026/how-to-clean-up-threadlocals and I'm not even sure if it is relevant.

**Comment by beeender** [comment]
Is that the full stack trace? that doesn't look like something would cause a stack overflow.
I didn't see `OnClientGetRoomHistoryResponse` in the stack trace? It should be a really long call stack and possibly show a infinite recursion call in the stack trace. @saeedrooyekhat

**Comment by saeedrooyekhat** [comment]
Hello Again!

I got an error to get the high number of realm instance. after solving this problem with reducing getInstance i wasn't faced with the stackoverflow error.

also following error was solved after that i disabled animation for this recycler view

```java
java.lang.NoSuchMethodError: io.realm.RealmResults.getTableOrView
at io.realm.RealmBasedRecyclerViewAdapter.<init>(RealmBasedRecyclerViewAdapter.java:167)
at io.realm.RealmBasedRecyclerViewAdapter.<init>(RealmBasedRecyclerViewAdapter.java:133)
```

(:

**Comment by Zhuinden** [comment]
`RealmBasedRecyclerViewAdapter` doesn't support Realm 3.0.0 though, so you can get animations with `RealmRecyclerViewAdapter`

**Comment by saeedrooyekhat** [comment]
yes that's true but now i don't have time for this change. i will be use later from RealmRecyclerViewAdapter.  thanks for your reminders @Zhuinden
