### ISSUE TITLE
RealmObject.getClass().getMethods() causes ClassNotFoundException on KitKat

### ISSUE THREAD

**Issue by purpleankh** [realm/realm-java#2094]
I'm using getMethods() on a RealmObject to programmatically find an appropriate setter method while parsing in an XML file. This worked fine with Realm up to 0.86.2. This continues to work fine on Lollipop and Marshmallow with Realm >= 0.87.0. However with KitKat I get the following exception:

```
01-15 13:40:55.074 1600-1600/test.local.realmtest1 W/dalvikvm: Unable to match class for part: 'Lrx/Observable;'
01-15 13:40:55.074 1600-1600/test.local.realmtest1 D/AndroidRuntime: Shutting down VM
01-15 13:40:55.074 1600-1600/test.local.realmtest1 W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4ca2b20)
01-15 13:40:55.074 1600-1600/test.local.realmtest1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: test.local.realmtest1, PID: 1600
                                                                     java.lang.NoClassDefFoundError: rx/Observable
                                                                         at java.lang.Class.getDeclaredMethods(Native Method)
                                                                         at java.lang.Class.getPublicMethodsRecursive(Class.java:894)
                                                                         at java.lang.Class.getMethods(Class.java:877)
                                                                         at test.local.realmtest1.MainActivity.addFields(MainActivity.java:28)
                                                                         at test.local.realmtest1.MainActivity.onCreate(MainActivity.java:16)
                                                                         at android.app.Activity.performCreate(Activity.java:5231)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                         at dalvik.system.NativeStart.main(Native Method)
                                                                      Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.Observable" on path: DexPathList[[zip file "/data/app/test.local.realmtest1-1.apk"],nativeLibraryDirectories=[/data/app-lib/test.local.realmtest1-1, /system/lib]]
                                                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                         at java.lang.Class.getDeclaredMethods(Native Method) 
                                                                         at java.lang.Class.getPublicMethodsRecursive(Class.java:894) 
                                                                         at java.lang.Class.getMethods(Class.java:877) 
                                                                         at test.local.realmtest1.MainActivity.addFields(MainActivity.java:28) 
                                                                         at test.local.realmtest1.MainActivity.onCreate(MainActivity.java:16) 
                                                                         at android.app.Activity.performCreate(Activity.java:5231) 
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:136) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                         at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                         at dalvik.system.NativeStart.main(Native Method) 
```
My testing environment is 3 different Genymotion Virtual machines based on a Nexus 5(X) configured for APIs 19, 22 & 23.
Note: I don't have a KitKat phone to hand to verify if this is related to the Genymotion virtual machine.

**Comment by cmelchior** [comment]
It is caused by our RxJava support being optional, so if you don't have `RxJava` on the classpath when interacting with our class the reflection API apparently throws an exception on KitKat. It sounds like a bug in KitKat, but since that is hardly getting fixed you will have to find a work-around.

If you do not wish to add RxJava as a dependency the easiest is to add a dummy class `rx.Observable` class as described here: https://realm.io/docs/java/latest/#jackson-databind

I am not sure if you can tell the reflection API to only return the methods on your exact type, but that would also be an solution.

Note that if you are dynamically parsing an XML file, using our Dynamic API is probably a better solution: https://realm.io/docs/java/latest/#dynamic-realms

**Comment by purpleankh** [comment]
After more experiments, I've been able to get the ```ClassNotFoundException``` in Lollipop and Marshmallow - it appears that the Runtime in these versions delays trying to load ```rx.Observable``` until absolutely necessary, whereas KitKat seems to preload all necessary classes.

In my case Dynamic Realms aren't necessary as the table and fields will be specified fully. The reason I want to parse dynamically is there are many dozens of fields to populate and I don't want to keep adjusting the parsing code when the Schema changes.

Creating the dummy ```rx.Observable``` does the trick, and allows things to run as before; although it does feel a little like a bodge.

It may be better to replace the ```getClass().getMethods()``` calls with ```RealmObjectSchema``` calls and then look for an explicit method with ```getClass().getMethod([Name],[Type].class)``` once I know the parameter type.

Cheers.
