### ISSUE TITLE
Error: cannot find symbol variable PersonRealmProxy

### ISSUE THREAD

**Issue by Queatz** [realm/realm-java#964]
Updated to version 0.80.0 and I get one of these errors per object type I have when building and the build fails.  0.79.1 works ok.

**Comment by cmelchior** [comment]
It sounds like a Gradle cache error.
Does this also happen if you do a ```./gradlew clean assemble``` from the command line?

**Comment by Queatz** [comment]
That command fails with the same error:

```

Jacobs-MacBook-Air:snappy jacob$ ./gradlew clean assemble
:app:clean
:app:preBuild
:app:compileDebugNdk
:app:preDebugBuild
:app:checkDebugManifest
:app:preReleaseBuild
:app:prepareComAndroidSupportAppcompatV72103Library
:app:prepareComAndroidSupportCardviewV72103Library
:app:prepareComAndroidSupportSupportV42103Library
:app:prepareComGoogleAndroidGmsPlayServices6587Library
:app:prepareComMakeramenRoundedimageview150Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3/res/drawable-xhdpi/abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3/res/drawable-hdpi/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3/res/drawable-hdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3/res/drawable-hdpi/abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3/res/drawable-xhdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/21.0.3/res/drawable-mdpi/abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:compileDebugJava
Note: Processing class Contact
Note: Processing class Follow
Note: Processing class Join
Note: Processing class Location
Note: Getter getText is not associated to any field
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:121: error: cannot find symbol
                PersonRealmProxy.initTable(transaction);
                ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:125: error: cannot find symbol
                PersonRealmProxy.initTable(transaction);
                ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:129: error: cannot find symbol
                MessageRealmProxy.initTable(transaction);
                ^
  symbol:   variable MessageRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:211: error: cannot find symbol
            PersonRealmProxy.populateUsingJsonObject(person, json.getJSONObject("person"));
            ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:216: error: cannot find symbol
            PersonRealmProxy.populateUsingJsonObject(contact, json.getJSONObject("contact"));
            ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:221: error: cannot find symbol
            MessageRealmProxy.populateUsingJsonObject(last, json.getJSONObject("last"));
            ^
  symbol:   variable MessageRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:249: error: cannot find symbol
                PersonRealmProxy.populateUsingJsonStream(personObj, reader);
                ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:253: error: cannot find symbol
                PersonRealmProxy.populateUsingJsonStream(contactObj, reader);
                ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:257: error: cannot find symbol
                MessageRealmProxy.populateUsingJsonStream(lastObj, reader);
                ^
  symbol:   variable MessageRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:292: error: cannot find symbol
                realmObject.setPerson(PersonRealmProxy.copyOrUpdate(realm, personObj, update, cache));
                                      ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:302: error: cannot find symbol
                realmObject.setContact(PersonRealmProxy.copyOrUpdate(realm, contactObj, update, cache));
                                       ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:312: error: cannot find symbol
                realmObject.setLast(MessageRealmProxy.copyOrUpdate(realm, lastObj, update, cache));
                                    ^
  symbol:   variable MessageRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:328: error: cannot find symbol
                realmObject.setPerson(PersonRealmProxy.copyOrUpdate(realm, personObj, true, cache));
                                      ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:339: error: cannot find symbol
                realmObject.setContact(PersonRealmProxy.copyOrUpdate(realm, contactObj, true, cache));
                                       ^
  symbol:   variable PersonRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/ContactRealmProxy.java:350: error: cannot find symbol
                realmObject.setLast(MessageRealmProxy.copyOrUpdate(realm, lastObj, true, cache));
                                    ^
  symbol:   variable MessageRealmProxy
  location: class ContactRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:79: error: cannot find symbol
                PersonRealmProxy.initTable(transaction);
                ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:83: error: cannot find symbol
                PersonRealmProxy.initTable(transaction);
                ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:142: error: cannot find symbol
            PersonRealmProxy.populateUsingJsonObject(person, json.getJSONObject("person"));
            ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:147: error: cannot find symbol
            PersonRealmProxy.populateUsingJsonObject(following, json.getJSONObject("following"));
            ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:162: error: cannot find symbol
                PersonRealmProxy.populateUsingJsonStream(personObj, reader);
                ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:166: error: cannot find symbol
                PersonRealmProxy.populateUsingJsonStream(followingObj, reader);
                ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:190: error: cannot find symbol
                realmObject.setPerson(PersonRealmProxy.copyOrUpdate(realm, personObj, update, cache));
                                      ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:200: error: cannot find symbol
                realmObject.setFollowing(PersonRealmProxy.copyOrUpdate(realm, followingObj, update, cache));
                                         ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:214: error: cannot find symbol
                realmObject.setPerson(PersonRealmProxy.copyOrUpdate(realm, personObj, true, cache));
                                      ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/FollowRealmProxy.java:225: error: cannot find symbol
                realmObject.setFollowing(PersonRealmProxy.copyOrUpdate(realm, followingObj, true, cache));
                                         ^
  symbol:   variable PersonRealmProxy
  location: class FollowRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:93: error: cannot find symbol
                PartyRealmProxy.initTable(transaction);
                ^
  symbol:   variable PartyRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:97: error: cannot find symbol
                PersonRealmProxy.initTable(transaction);
                ^
  symbol:   variable PersonRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:165: error: cannot find symbol
            PartyRealmProxy.populateUsingJsonObject(party, json.getJSONObject("party"));
            ^
  symbol:   variable PartyRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:170: error: cannot find symbol
            PersonRealmProxy.populateUsingJsonObject(person, json.getJSONObject("person"));
            ^
  symbol:   variable PersonRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:187: error: cannot find symbol
                PartyRealmProxy.populateUsingJsonStream(partyObj, reader);
                ^
  symbol:   variable PartyRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:191: error: cannot find symbol
                PersonRealmProxy.populateUsingJsonStream(personObj, reader);
                ^
  symbol:   variable PersonRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:216: error: cannot find symbol
                realmObject.setParty(PartyRealmProxy.copyOrUpdate(realm, partyObj, update, cache));
                                     ^
  symbol:   variable PartyRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:226: error: cannot find symbol
                realmObject.setPerson(PersonRealmProxy.copyOrUpdate(realm, personObj, update, cache));
                                      ^
  symbol:   variable PersonRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:241: error: cannot find symbol
                realmObject.setParty(PartyRealmProxy.copyOrUpdate(realm, partyObj, true, cache));
                                     ^
  symbol:   variable PartyRealmProxy
  location: class JoinRealmProxy
/Users/jacob/Documents/Snappy/snappy/app/build/intermediates/classes/debug/io/realm/JoinRealmProxy.java:252: error: cannot find symbol
                realmObject.setPerson(PersonRealmProxy.copyOrUpdate(realm, personObj, true, cache));
                                      ^
  symbol:   variable PersonRealmProxy
  location: class JoinRealmProxy
Note: /Users/jacob/Documents/Snappy/snappy/app/src/main/java/com/queatz/snappy/team/Things.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/jacob/Documents/Snappy/snappy/app/src/main/java/com/queatz/snappy/team/Things.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
35 errors
:app:compileDebugJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 34.692 secs
```

**Comment by Queatz** [comment]
Maybe it's because I have custom methods in my RealmObjects?

**Comment by cmelchior** [comment]
It doesn't look like your Person class is being processed by the annotation processor. Does your Person class extend RealmObject or is it missing the @RealmClass annotation?

Custom methods are not allowed, but in 0.80.0 they only output a warning. If you use a SNAPSHOT it should throw a proper error, but not crash the build like it currently does.

**Comment by Queatz** [comment]
My Person class looks like this.  It looks okay?  I haven't been using @RealmClass.

```java
public class Person extends RealmObject {
    @Index
    private String id;
    private String firstName;
    private String lastName;
    private String about;
    private String imageUrl;
    private long infoFollowers;
    private long infoFollowing;
    private long infoHosted;
    private RealmList<Update> updates;
    private RealmList<Message> messages;
    private RealmList<Follow> followers;
    private RealmList<Follow> following;

    public String getName() {
        return getFirstName() + " " + getLastName();
    }

    public String getImageUrlForSize(int size) {
        if(getImageUrl() == null || getImageUrl().isEmpty() || !getImageUrl().contains("="))
            return null;

        return getImageUrl().split("=")[0] + "=" + size;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAbout() {
        return about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public long getInfoFollowers() {
        return infoFollowers;
    }

    public void setInfoFollowers(long infoFollowers) {
        this.infoFollowers = infoFollowers;
    }

    public long getInfoFollowing() {
        return infoFollowing;
    }

    public void setInfoFollowing(long infoFollowing) {
        this.infoFollowing = infoFollowing;
    }

    public long getInfoHosted() {
        return infoHosted;
    }

    public void setInfoHosted(long infoHosted) {
        this.infoHosted = infoHosted;
    }

    public RealmList<Update> getUpdates() {
        return updates;
    }

    public void setUpdates(RealmList<Update> updates) {
        this.updates = updates;
    }

    public RealmList<Message> getMessages() {
        return messages;
    }

    public void setMessages(RealmList<Message> messages) {
        this.messages = messages;
    }

    public RealmList<Follow> getFollowers() {
        return followers;
    }

    public void setFollowers(RealmList<Follow> followers) {
        this.followers = followers;
    }

    public RealmList<Follow> getFollowing() {
        return following;
    }

    public void setFollowing(RealmList<Follow> following) {
        this.following = following;
    }
}
```

**Comment by cmelchior** [comment]
That should be OK. Have you tried removing the Location.getText()? The annotation processor outputs a warning about it.

**Comment by Queatz** [comment]
The errors still persisted after removing Location.getText().  If I find something more I'll let you know, going to stick with 0.79.1 for now.

**Comment by emanuelez** [comment]
You are using custom methods, which is not allows right now in Realm (neither 0.79.1 nor 0.80.0).
My suggestion is to use a util class with static methods for such functionality.

**Comment by jyzhang** [comment]
Hey guys... I'm having the same issue! There's must be a bug in the pre-compiler / code generator... this worked fine in 0.79.1. I need 0.80.0 because it fixes crash bug when removing last item from RealmList.

My Playlist class is very simple

```Java
public class Playlist extends RealmObject {

    private String title;

    @PrimaryKey
    private int id;
    private int total;
    private RealmList<Track> tracks;

    public Playlist() {}

    public Playlist(int playlistId) {
        this.id = playlistId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public RealmList<Track> getTracks() {
        return tracks;
    }

    public void setTracks(RealmList<Track> tracks) {
        this.tracks = tracks;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getTotal() {
        return total;
    }

    public void setTotal(int total) {
        this.total = total;
    }
}
```
I get: `error: cannot find symbol variable TrackRealmProxy` when I try to compile. The generated PlaylistRealmProxy can't find TrackRealmProxy

```Java
public static Table initTable(ImplicitTransaction transaction) {
        if(!transaction.hasTable("class_Playlist")) {
            Table table = transaction.getTable("class_Playlist");
            table.addColumn(ColumnType.STRING, "title");
            table.addColumn(ColumnType.INTEGER, "id");
            table.addColumn(ColumnType.INTEGER, "total");
            if (!transaction.hasTable("class_Track")) {
                TrackRealmProxy.initTable(transaction);
            }
            table.addColumnLink(ColumnType.LINK_LIST, "tracks", transaction.getTable("class_Track"));
            table.setPrimaryKey("id");
            return table;
        }
        return transaction.getTable("class_Playlist");
    }
```

**Comment by cmelchior** [comment]
Hi @jyzhang 
How does your Track class look like?

**Comment by jyzhang** [comment]
I actually fixed the problem... by removing all non-getter/setter methods from Track class.

The compiler should probably be updated to generate the correct error message for Track class instead of breaking on Playlist.

**Comment by cmelchior** [comment]
@jyzhang Great you found the error. At least from 0.80.0, the compiler should actually complain in your case. Are you using Eclipse? Because we heard from a few users complaining about the same as you, so there might be some issue with how Eclipse handles caching and logging of the annotation processor that makes it not totally transparent that there is an error.

**Comment by jyzhang** [comment]
I'm using android studio 1.1.0

**Comment by cmelchior** [comment]
Hi @jyzhang 
I just checked the behaviour in Android Studio, and it correctly outputs and error in that case, at least if you look in the Gradle Console. 

Can you reproduce this behavior in a fresh project?

**Comment by Toolenaar** [comment]
Having the same problems. Reverted back to 0.79.1 for now. 

Error:(139, 17) error: cannot find symbol variable MemuTrackRealmProxy
Error:(248, 17) error: cannot find symbol variable MemuTrackRealmProxy
Error:(281, 21) error: cannot find symbol variable MemuTrackRealmProxy
Error:(336, 41) error: cannot find symbol variable MemuTrackRealmProxy
Error:(361, 41) error: cannot find symbol variable MemuTrackRealmProxy
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\jochem\Source\Repos\github\memu-android\app\src\main\java\com\jtms\memu\logic\music\jukebox\PlaylistGenerator.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Error:Execution failed for task ':app:compileDebugJava'.
> Compilation failed; see the compiler error output for details.

**Comment by emanuelez** [comment]
@Toolenaar would you please share your model classes? Are you using custom methods?

**Comment by Toolenaar** [comment]
I am using some custom methods but these did work before. Here is a gist with my realm classes. Hope it helps. https://gist.github.com/Toolenaar/a2011b4f145d46846a3d

**Comment by emanuelez** [comment]
@Toolenaar Thank you. Can you please also provide the output of a gradle build?

**Comment by cmelchior** [comment]
Hi @Toolenaar 
I assume you got it to work, please reopen with the output of the gradle build if that is not the case.

**Comment by droidahmed** [comment]
public class AyatText implements RealmModel {

    public String ayatText;
    public String suraNum;
    public String ayaNum;

    public AyatText() {
    }

    public AyatText(String ayatText, String suraNum, String ayaNum) {
        this.ayatText = ayatText;
        this.suraNum = suraNum;
        this.ayaNum = ayaNum;
    }

    public String getAyatText() {
        return ayatText;
    }

    public void setAyatText(String ayatText) {
        this.ayatText = ayatText;
    }

    public String getSuraNum() {
        return suraNum;
    }

    public void setSuraNum(String suraNum) {
        this.suraNum = suraNum;
    }

    public String getAyaNum() {
        return ayaNum;
    }

    public void setAyaNum(String ayaNum) {
        this.ayaNum = ayaNum;
    }

    @Override
    public String toString() {
        return "AyatText{" +
                "ayatText='" + ayatText + '\'' +
                ", suraNum='" + suraNum + '\'' +
                ", ayaNum='" + ayaNum + '\'' +
                '}';
    }
}


    public static Table initTable(ImplicitTransaction transaction) {
        if (!transaction.hasTable("class_InfoTafseer")) {
            Table table = transaction.getTable("class_InfoTafseer");
            table.addColumn(RealmFieldType.STRING, "ayaText", Table.NULLABLE);
            if (!transaction.hasTable("class_Tafser")) {
                TafserRealmProxy.initTable(transaction);
            }
            table.addColumnLink(RealmFieldType.LIST, "tafserRealmList", transaction.getTable("class_Tafser"));
            table.addColumn(RealmFieldType.STRING, "sora", Table.NULLABLE);
            table.addColumn(RealmFieldType.STRING, "suraNum", Table.NULLABLE);
            if (!transaction.hasTable("class_AyatText")) {
                AyatTextRealmProxy.initTable(transaction);
            }

Error:(255, 17) error: cannot find symbol variable AyatTextRealmProxy

        classpath "io.realm:realm-gradle-plugin:1.1.0"

**Comment by beeender** [comment]
@droidahmed Are you using kotlin? if yes, try with the `1.2.0-SNAPSHOT`

**Comment by droidahmed** [comment]
no I use java 8

**Comment by beeender** [comment]
@droidahmed Are you using jack compiler? There is a known issue with jack compiler and google transform API. See #3038
